/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:249331:
  println("button1 - GButton event occured " + System.currentTimeMillis()%10000000 );
  port.write(255);
  background(230);
  stroke(0,0,0);
  fill(0,0,0);
  rect(BORDER-1, BORDER-1, 640, 640);
  port.write(254);
} //_CODE_:button1:249331:

public void Red(GTextField source, GEvent event) { //_CODE_:Text_Red:734726:
  println("r - GTextField event occured " + System.currentTimeMillis()%10000000 );
  r = int(Text_Red.getText())%256;
} //_CODE_:Text_Red:734726:

public void Green(GTextField source, GEvent event) { //_CODE_:Text_Green:607267:
  println("g - GTextField event occured " + System.currentTimeMillis()%10000000 );
  g = int(Text_Green.getText())%256;
} //_CODE_:Text_Green:607267:

public void Blue(GTextField source, GEvent event) { //_CODE_:Text_Blue:407576:
  println("b - GTextField event occured " + System.currentTimeMillis()%10000000 );
  b = int(Text_Blue.getText())%256;
} //_CODE_:Text_Blue:407576:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:COM_PORT:368153:
  println("COM_PORT - GTextField event occured " + System.currentTimeMillis()%10000000 );
  if(COM_PORT_NUM != int(COM_PORT.getText()))
  {
    COM_PORT_NUM = int(COM_PORT.getText());
    port = new Serial(this, Serial.list()[COM_PORT_NUM], 9600); 
    flag = boolean(0);
  }
} //_CODE_:COM_PORT:368153:


// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  
  button1 = new GButton(this, 510, 675, 80, 30);
  button1.setText("Clear");
  button1.addEventHandler(this, "button1_click1");


  label1 = new GLabel(this, 30, 650, 80, 20);
  label1.setText("Red:");
  label1.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label1.setOpaque(false);
  Text_Red = new GTextField(this, 30, 675, 81, 30, G4P.SCROLLBARS_NONE);
  Text_Red.setText("0");
  Text_Red.setOpaque(true);
  Text_Red.addEventHandler(this, "Red");
  
  label3 = new GLabel(this, 150, 650, 80, 20);
  label3.setText("Green:");
  label3.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label3.setOpaque(false);
  Text_Green = new GTextField(this, 150, 675, 81, 30, G4P.SCROLLBARS_NONE);
  Text_Green.setText("0");
  Text_Green.setOpaque(true);
  Text_Green.addEventHandler(this, "Green");
  
  label2 = new GLabel(this, 270, 650, 80, 20);
  label2.setText("Blue:");
  label2.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label2.setOpaque(false);
  Text_Blue = new GTextField(this, 270, 675, 81, 30, G4P.SCROLLBARS_NONE);
  Text_Blue.setText("0");
  Text_Blue.setOpaque(true);
  Text_Blue.addEventHandler(this, "Blue");
  
  COM_PORT = new GTextField(this, 390, 675, 81, 30, G4P.SCROLLBARS_NONE);
  COM_PORT.setText("0");
  COM_PORT.setOpaque(true);
  COM_PORT.addEventHandler(this, "textfield1_change1");
  label4 = new GLabel(this, 390, 650, 80, 20);
  label4.setText("COM PORT");
  label4.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label4.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GTextField Text_Red; 
GTextField Text_Green; 
GLabel label1; 
GTextField Text_Blue; 
GLabel label3; 
GLabel label2; 
GTextField COM_PORT; 
GLabel label4; 

